# Generated by Django 5.2.14 on 2026-06-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('note', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami')),
                ('status', models.CharField(choices=[('new', '🆕 Yangi'), ('confirmed', '✅ Tasdiqlangan'), ('in_delivery', '🚚 Yetkazilmoqda'), ('delivered', '📦 Yetkazildi'), ('cancelled', '❌ Bekor qilindi')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Buyurtma yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['telegram_id', 'status'], name='orders_orde_telegra_b95be7_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Buyurtma mahsuloti',
                'verbose_name_plural': 'Buyurtma mahsulotlari',
            },
        ),
    ]
