# Generated by Django 5.2.14 on 2026-06-12 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryservice_icon'),
        ('orders', '0002_alter_order_total_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.servicebranch', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Yetkazib berish narxi'),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.district', verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_tashkent_city',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_taxi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.region', verbose_name='Viloyat'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryservice', verbose_name='Yetkazib berish xizmati'),
        ),
        migrations.AddField(
            model_name='order',
            name='uzpost_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='UzPost manzili'),
        ),
    ]
