# Generated by Django 5.2.14 on 2026-06-15 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0003_order_branch_order_delivery_price_order_district_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_telegra_b95be7_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clients.client', verbose_name='Mijoz'),
        ),
    ]
