# Generated by Django 5.2.14 on 2026-06-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_orders_orde_telegra_b95be7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('card', 'Plastik'), ('cash', 'Naqd')], null=True, verbose_name="To'lov turi"),
        ),
    ]
