# Generated by Django 5.2.14 on 2026-06-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'To‘lanmagan'), ('partial', 'Yarmini to‘ladi'), ('paid', 'To‘liq to‘ladi')], default='not_paid', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlangan'), ('in_delivery', 'Yetkazilmoqda'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='new', max_length=20),
        ),
    ]
