# Generated by Django 5.2.14 on 2026-06-19 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientaddress'),
        ('orders', '0006_order_payment_status_order_telegram_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clientaddress', verbose_name='Saqlangan manzil'),
        ),
    ]
