# Generated by Django 5.2.14 on 2026-06-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Kiriting...', max_length=20, verbose_name="To'lov holati"),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlangan'), ('in_delivery', 'Yetkazilmoqda'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='new', max_length=20, verbose_name='Buyurtma holati'),
        ),
    ]
