# Generated by Django 5.2.14 on 2026-06-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Kiritilmagan', max_length=20, verbose_name="To'lov holati"),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlangan'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='new', max_length=20, verbose_name='Buyurtma holati'),
        ),
    ]
