# Generated by Django 5.2.14 on 2026-06-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryservice',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/services/'),
        ),
    ]
