# Generated by Django 5.2.14 on 2026-06-19 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('delivery', '0002_deliveryservice_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', help_text='Uy, Ish, Onam uyiga va h.k.', max_length=50, verbose_name='Nomi')),
                ('address', models.CharField(max_length=500, verbose_name='Manzil')),
                ('building', models.CharField(blank=True, default='', max_length=50)),
                ('apartment', models.CharField(blank=True, default='', max_length=50)),
                ('intercom', models.CharField(blank=True, default='', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clients.client')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.district')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.region')),
            ],
            options={
                'verbose_name': 'Mijoz manzili',
                'verbose_name_plural': 'Mijoz manzillari',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
