# Generated by Django 5.2.14 on 2026-05-31 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True, help_text='Bosilganda ochiluvchi link (ixtiyoriy)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon_slug', models.CharField(choices=[('apple', '🍎 Olma (mevalar)'), ('nuts', "🥜 Yong'oqlar (quruq mevalar)"), ('melon', '🍉 Tarvuz (poliz)'), ('grain', '🌾 Don (dukkaklilar)'), ('bread', '🍞 Non (un mahsulotlari)'), ('meat', "🥩 Go'sht"), ('milk', '🥛 Sut'), ('olive', "🫒 Zaytun (yog'lar)"), ('vinegar', '🍶 Sirka'), ('herb', '🌿 Giyoh'), ('organic', '🌱 Organik'), ('tea', '☕ Choy/qahva'), ('honey', '🍯 Asal/murabbo'), ('ready-meal', '🍲 Tayyor taom'), ('candy', '🍬 Shirinlik')], default='organic', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Tartib (kichikroq = oldinroq)', verbose_name='Tartib joylashuvi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faollik holati')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Mahsulot surati')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('g', 'gramm'), ('l', 'litr'), ('piece', 'dona'), ('pack', 'paket')], default='kg', max_length=10, verbose_name="O'lchov birligi")),
                ('is_organic', models.BooleanField(default=True, help_text='Organik yorliqli mahsulot')),
                ('is_available', models.BooleanField(default=True, verbose_name='Sotuvda mavjudlik holati')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Miqdori')),
                ('is_preorder', models.BooleanField(default=False, verbose_name='Oldindan buyurtma olinadimi?')),
                ('preorder_threshold', models.PositiveIntegerField(default=0, verbose_name='Buyurtmani tasdiqlash uchun minimal miqdor')),
                ('preorder_deadline', models.DateTimeField(blank=True, null=True, verbose_name="Buyurtma yig'ish tugash vaqti")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Kategoriya nomi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_available'], name='products_pr_categor_c898cc_idx')],
            },
        ),
    ]
