# Generated by Django 5.2.14 on 2026-06-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preorder_threshold',
            field=models.PositiveIntegerField(default=0, verbose_name='Buyurtmani tasdiqlash uchun maksimal miqdor'),
        ),
    ]
