# Generated by Django 5.2.14 on 2026-06-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_preorder_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preorder_period_started_at',
            field=models.DateTimeField(blank=True, help_text='Faqat shu vaqtdan keyingi buyurtmalar hisobga olinadi', null=True, verbose_name='Joriy qabul boshlangan vaqt'),
        ),
    ]
