# Generated by Django 5.2.14 on 2026-06-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostRegions',
        ),
    ]
